server:
  port: 0

spring:
  application:
    name: project-service



eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    preferIpAddress: true
    instance-id:  ${spring.application.name}:${random.int}

onesearch:
  service:
    url: http://onesearch-service/
