server:
  port: 0
spring:
  application:
    name: onesearch-service
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int} # random.int or random.value
    prefer-ip-address: true

